### ISSUE TITLE
Missing Comma in package.json Causes npm Install Failure

### ISSUE THREAD

**Issue by gtchakama** [JawherKl/node-api-postgres#18]
## Issue Description
When running `npm install`, the installation fails due to a JSON syntax error in `package.json`.

## Error Details
![image](https://github.com/user-attachments/assets/f2711a82-639c-4c11-b000-12bf47e3dce2)

## Location
The error occurs in `package.json` on line 56, specifically:

![image](https://github.com/user-attachments/assets/c10dcce9-de33-4bb8-aaef-c8c8de2233c9)

**Comment by JawherKl** [comment]
Fixed! Added the missing comma to `package.json`. Thank you for pointing it out! 😊

**Comment by JawherKl** [comment]
Fixed! Added the missing comma to `package.json`. Thank you for pointing it out! 😊
